language: go

go:
  - 1.3

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script: 
  - go test ./ -v
  - go test ./models -v
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken Yn4YO7sx7LGpUldSEqFlHt6RER6QQ1fQQ

before_script:
  - mysql -e 'create database blog_test;'
